# based on Eric Herlitz's sample pipeline
# http://www.herlitz.nu/2019/09/12/yaml-to-build-.net-core-3-on-azure-devops/

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  projects: '**/*.csproj'
  testProjects: '**/*.XUnit/*.csproj'
  nugetVersion: '5.2.0' # https://dist.nuget.org/tools.json

steps:
- task: UseDotNet@2
  displayName: 'Use dotnet sdk 3.x'
  inputs:
    version: 3.x
    includePreviewVersions: true

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: $(nugetVersion) 
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: $(solution)
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(projects)
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: $(testProjects)